### ISSUE TITLE
20230920 Feedback

### ISSUE THREAD

**Issue by MisooKim2** [cksals0316/C202309#1]
challenge/week3/choiceIf	no file
challenge/week3/zeroTwoIf	no file

위 두 파일에서 I는 L이 아니라 i 대문자입니다.

**Comment by cksals0316** [comment]
C202309 파일에 가서 잘못된 부분의 이름을 고치고 다시 깃허브에 커밋 후 푸쉬

**Comment by cksals0316** [comment]
C202309 파일에 가서 잘못된 부분의 이름을 고치고 다시 깃허브에 커밋 후 푸쉬
