### ISSUE TITLE
20231031 중간 이전 전체 검토 결과

### ISSUE THREAD

**Issue by MisooKim2** [cksals0316/C202309#3]
### 없는 파일
- challenge/week5/functionMulti.c
- practice/week5/functionHap.c
	- 위 파일 이름이나 위치를 다시 확인하세요. 해당 소스 파일 채점이 수행되지 않습니다.

**Comment by cksals0316** [comment]
파일 이름 바꾸고 커밋 후 푸쉬 했습니다.
